import { IconType } from "react-icons/lib";
import {
  WiCloudy,
  WiDayCloudy,
  WiDayFog,
  WiDayHaze,
  WiDayShowers,
  WiDaySunny,
  WiDust,
  WiHurricane,
  WiNightAltCloudy,
  WiNightAltShowers,
  WiNightClear,
  WiNightFog,
  WiRain,
  WiRainMix,
  WiSnow,
  WiSnowflakeCold,
  WiThunderstorm,
  WiWindy,
} from "react-icons/wi";

export const getIcon = (icon: string, isNight: boolean) => isNight ? weatherIconNight[icon] : undefined ?? weatherIcon[icon]

export const weatherIcon: {[key: string]: IconType} = {
  clear: WiNightClear,
  cloudy: WiCloudy,
  cyclone: WiHurricane,
  dust: WiDust,
  dusty: WiDust,
  fog: WiDayFog,
  frost: WiSnowflakeCold,
  haze: WiDayHaze,
  hazy: WiDayHaze,
  heavy_shower: WiRain,
  heavy_showers: WiRain,
  light_rain: WiRainMix,
  light_shower: WiDayShowers,
  light_showers: WiDayShowers,
  mostly_sunny: WiDayCloudy,
  partly_cloudy: WiDayCloudy,
  rain: WiRain,
  shower: WiDayShowers,
  showers: WiDayShowers,
  snow: WiSnow,
  storm: WiThunderstorm,
  storms: WiThunderstorm,
  sunny: WiDaySunny,
  tropical_cyclone: WiHurricane,
  wind: WiWindy,
  windy: WiWindy,
};

export const weatherIconNight: {[key: string]: IconType} = {
  fog: WiNightFog,
  light_shower: WiNightAltShowers,
  light_showers: WiNightAltShowers,
  mostly_sunny: WiNightAltCloudy,
  partly_cloudy: WiNightAltCloudy,
  shower: WiNightAltShowers,
  showers: WiNightAltShowers,
  sunny: WiNightClear,
};
